services:
  backend:
    build: ./mern/backend        # backend Dockerfile থেকে build হবে
    ports:
      - "5050:5050"              # host:container port mapping
    networks:
      - mern_network             # backend একই network এ
    depends_on:
      - mongodb                  # mongodb আগে start হবে

  mongodb:
    image: mongo:latest           # official mongo image use করা হচ্ছে
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db       # data persistence

  frontend:
    build: ./mern/frontend        # frontend Dockerfile থেকে build হবে
    ports:
      - "5173:5173"
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge                 # private bridge network

volumes:
  mongo-data:
    driver: local                  # local volume
