name: Build & Deploy MERN Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -t rhkonok/mern-backend:latest ./mern/backend
          docker push rhkonok/mern-backend:latest

      - name: Build & push frontend image
        run: |
          docker build -t rhkonok/mern-frontend:latest ./mern/frontend
          docker push rhkonok/mern-frontend:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.6.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/mern
            git pull origin main
            docker compose down
            docker compose up -d --build
