name: Build & Deploy MERN Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RHKONOK }}          # Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Personal Access Token

      # 4️⃣ Build & push backend image
      - name: Build & push backend image
        run: |
          docker build -t rhkonok/mern-backend:latest ./mern/backend
          docker push rhkonok/mern-backend:latest

      # 5️⃣ Build & push frontend image
      - name: Build & push frontend image
        run: |
          docker build -t rhkonok/mern-frontend:latest ./mern/frontend
          docker push rhkonok/mern-frontend:latest

      # 6️⃣ Deploy to server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/mern
            git pull origin main
            docker compose down
            docker compose up -d --build
