name: Build & Deploy MERN Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug - list files
      - name: List repository files
        run: ls -R

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Docker Hub Login
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 5: Build & Push Backend
      - name: Build & Push Backend
        run: |
          cd ./backend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest

      # Step 6: Build & Push Frontend
      - name: Build & Push Frontend
        run: |
          cd ./frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest

      # Step 7: Push MongoDB official image
      - name: Push MongoDB
        run: |
          docker pull mongo:latest
          docker tag mongo:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mern-mongodb:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-mongodb:latest

      # Optional Step 8: Deploy using docker-compose on server (requires SSH)
      #- name: Deploy via SSH
      #  uses: appleboy/ssh-action@v0.1.8
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USERNAME }}
      #    key: ${{ secrets.SSH_KEY }}
      #    script: |
      #      cd /home/${{ secrets.USERNAME }}/mern
      #      docker compose pull
      #      docker compose up -d --build
