name: Build & Push MERN Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          cd ./mern/backend
          docker build -t rhkonok/mern-backend:latest .
          docker push rhkonok/mern-backend:latest

      - name: Build & Push Frontend
        run: |
          cd ./mern/frontend
          docker build -t rhkonok/mern-frontend:latest .
          docker push rhkonok/mern-frontend:latest

      - name: Push MongoDB
        run: |
          docker pull mongo:7.0
          docker tag mongo:7.0 rhkonok/mern-mongodb:latest
          docker push rhkonok/mern-mongodb:latest
