name: Build & Deploy MERN Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -R

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Docker Hub Login
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 5: Build & Push Backend
      - name: Build & Push Backend
        run: |
          cd ./mern/backend
          docker build -t rhkonok/mern-backend:latest .
          docker push rhkonok/mern-backend:latest

      # Step 6: Build & Push Frontend
      - name: Build & Push Frontend
        run: |
          cd ./mern/frontend
          docker build -t rhkonok/mern-frontend:latest .
          docker push rhkonok/mern-frontend:latest

      # Step 7: Push MongoDB official image
      - name: Push MongoDB
        run: |
          docker pull mongo:7.0
          docker tag mongo:7.0 rhkonok/mern-mongodb:latest
          docker push rhkonok/mern-mongodb:latest
